version: '3'

volumes:
  pg_data_kitty:
  static_kitty:
  media_kitty:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    build: ./backend/
    env_file: .env
    # Тут подключаем volume к backend
    volumes:
      - static:/backend_static
    depends_on:
      - db
  frontend:
    env_file: .env
    build: ./frontend/
  gateway:
    build: ./gateway/
    # А тут подключаем volume со статикой к gateway
    volumes:
      - static:/staticfiles/
    ports:
      - 9000:80 
    depends_on:
      - backend