# docker-compose.production.yml
version: '3'

volumes:
  kittygram_final_pg_data_kitty_production:
  kittygram_final_static_kitty_production:
  kittygram_final_media_kitty_production:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - kittygram_final_pg_data_kitty_production:/var/lib/postgresql/data
  backend:
    image: deonisg/kittygram_backend
    env_file: .env
    volumes:
      - static_kitty_production:/backend_static/
      - media_kitty_production:/app/media/cats/images/
    depends_on:
    - db
  frontend:
    image: deonisg/kittygram_frontend  # Качаем с DockerHub
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_kitty_production:/frontend_static
  gateway:
    image: deonisg/kittygram_gateway  # Качаем с DockerHub
    # env_file: .env
    volumes:
      - static_kitty_production:/staticfiles/
      - media_kitty_production:/media/cats/images/
    ports:
      - 9000:80
    depends_on:
      - backend