version: '3'

volumes:
  pg_data_kitty:
  static_kitty:
  media_kitty:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_kitty:/var/lib/postgresql/data

  backend:
    build: ./backend/
    env_file: .env
    volumes:
      - static_kitty:/backend_static
    depends_on:
      - db

  frontend:
    env_file: .env
    build: ./frontend/

  gateway:
    build: ./gateway/
    volumes:
      - static_kitty:/staticfiles/
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      - backend
