version: '3'

volumes:
  pg_data_production:
  static_volume:

services:
  db:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data_production:/var/lib/postgresql/data

  backend:
    image: deonisg/kittygram_backend
    env_file: .env
    volumes:
      - static_volume:/backend_static
    depends_on:
      - db

  frontend:
    image: deonisg/kittygram_frontend
    env_file: .env
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static_volume:/frontend_static
    depends_on:
      - backend

  gateway:
    image: deonisg/kittygram_gateway
    env_file: .env
    volumes:
      - static_volume:/staticfiles/
    ports:
      - ${GATEWAY_PORT}:80
    depends_on:
      - backend